name = "atomic-ambitions-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".open-next/assets"

[[rules]]
type = "ESModule"
globs = [".open-next/worker.js"]
